# yaml-language-server: $schema=https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2023/08/config/document.json
$schema: https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2023/08/config/document.json
metadata:
  winget:
    processor:
      identifier: dscv3
resources:
  - type: Microsoft.WinGet/Package
    name: InstallBrave
    metadata:
      winget:
        securityContext: elevated
    properties:
      id: Brave.Brave
      source: winget

  - type: Microsoft.WinGet/Package
    name: InstallFirefox
    metadata:
      winget:
        securityContext: elevated
    properties:
      id: Mozilla.Firefox
      source: winget

  - type: Microsoft.WinGet/Package
    name: InstallNotepadPlusPlus
    metadata:
      winget:
        securityContext: elevated
    properties:
      id: Notepad++.Notepad++
      source: winget

  - type: Microsoft.WinGet/Package
    name: InstallWindowsTerminal
    metadata:
      winget:
        securityContext: elevated
    properties:
      id: Microsoft.WindowsTerminal
      source: winget

  - type: Microsoft.WinGet/Package
    name: InstallVLC
    metadata:
      winget:
        securityContext: elevated
    properties:
      id: VideoLAN.VLC
      source: winget

  - type: Microsoft.WinGet/Package
    name: InstallYtDlp
    metadata:
      winget:
        securityContext: elevated
    properties:
      id: yt-dlp.yt-dlp
      source: winget

  - type: Microsoft.WinGet/Package
    name: InstallFFmpeg
    metadata:
      winget:
        securityContext: elevated
    properties:
      id: yt-dlp.FFmpeg
      source: winget

  - type: Microsoft.WinGet/Package
    name: Install7zip
    metadata:
      winget:
        securityContext: elevated
    properties:
      id: 7zip.7zip
      source: winget

  - type: Microsoft.WinGet/Package
    name: InstallAdobeReader
    metadata:
      winget:
        securityContext: elevated
    properties:
      id: Adobe.Acrobat.Reader.64-bit
      source: winget

  - type: Microsoft.WinGet/Package
    name: InstallWinDirStat
    metadata:
      winget:
        securityContext: elevated
    properties:
      id: WinDirStat.WinDirStat
      source: winget

  - type: Microsoft.WinGet/Package
    name: InstallFlameshot
    metadata:
      winget:
        securityContext: elevated
    properties:
      id: Flameshot.Flameshot
      source: winget

  - type: Microsoft.WinGet/Package
    name: InstallMicrosoftTeams
    metadata:
      winget:
        securityContext: elevated
    properties:
      id: Microsoft.Teams
      source: winget

  - type: Microsoft.WinGet/Package
    name: InstallCaprine
    metadata:
      winget:
        securityContext: elevated
    properties:
      id: Caprine.Caprine
      source: winget

  - type: Microsoft.WinGet/Package
    name: InstallBrotheriPrintScan
    metadata:
      winget:
        securityContext: elevated
    properties:
      id: Brother.iPrintScan
      source: winget

  - type: Microsoft.WinGet/Package
    name: InstallCalibre
    metadata:
      winget:
        securityContext: elevated
    properties:
      id: calibre.calibre
      source: winget

  - type: Microsoft.WinGet/Package
    name: InstallSpotify
    metadata:
      winget:
        securityContext: elevated
    properties:
      id: Spotify.Spotify
      source: winget

  - type: Microsoft.WinGet/Package
    name: InstallShotcut
    metadata:
      winget:
        securityContext: elevated
    properties:
      id: Meltytech.Shotcut
      source: winget