# yaml-language-server: $schema=https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2023/08/config/document.json
$schema: https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2023/08/config/document.json
metadata:
  winget:
    processor:
      identifier: dscv3
resources:
  - type: Microsoft.WinGet/Package
    name: InstallOpenTofu
    metadata:
      winget:
        securityContext: elevated
    properties:
      id: OpenTofu.Tofu
      source: winget
      _exist: true

  - type: Microsoft.WinGet/Package
    name: InstallAwsCli
    metadata:
      winget:
        securityContext: elevated
    properties:
      id: Amazon.AWSCLI
      source: winget
      _exist: true