---
- name: Install packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - cifs-utils
    - curl
    - xserver-xorg-input-synaptics
    - xz-utils
    - nala

- name: Install synaptics-repository-keyring
  ansible.builtin.apt:
    deb: https://www.synaptics.com/sites/default/files/Ubuntu/pool/stable/main/all/synaptics-repository-keyring.deb
  notify:
    - Update APT cache

- meta: flush_handlers

- name: Install drivers
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - displaylink-driver

- name: Install apt applications
  ansible.builtin.apt:
    name: "{{ item }}"  
    state: present
  with_items:
    - google-chrome-stable
    - notepadqq
    - codium # Visual Studio Code
    - nordvpn
    - vlc

- name: Install flatpak applications
  community.general.flatpak:
    name: "{{ item }}"
    state: present
  with_items:
    - com.github.tchx84.Flatseal
    - com.spotify.Client
    - com.skype.Client
    - io.dbeaver.DBeaverCommunity
    - com.axosoft.GitKraken

- name: Install development tools
  ansible.builtin.apt:
    name: "{{ item }}"  
    state: present
  with_items:
    - git
    - python3
    - python3-pip
    - apache2
    - php
    - libapache2-mod-php
    - php-mysql
    - php-xml
    - php-curl
    - nodejs

- name: Install docker
  ansible.builtin.apt:
    name: "{{ item }}"  
    state: present
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin

- name: Install global npm packages
  community.general.npm:
    name: "{{ item }}"
    global: true
  with_items:
    - pnpm
    - turbo

- name: Install AWS CLI
  mdinicola.aws_tools_linux.aws_cli:
    state: present