---
- name: Add VSCodium APT repository
  ansible.builtin.deb822_repository:
    name: vscodium
    types: [deb]
    uris: https://download.vscodium.com/debs
    signed_by: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
    architectures: amd64
    suites: [vscodium]
    components: [main]
    state: present
    enabled: yes
  notify:
    - Update APT cache

- name: Add Docker Module Repository
  ansible.builtin.deb822_repository:
    name: docker
    types: [deb]
    uris: "https://download.docker.com/linux/ubuntu"
    signed_by: "https://download.docker.com/linux/ubuntu/gpg"
    architectures: amd64
    suites: ["{{ ubuntu_codename | lower }}"]
    components: [stable]
    state: present
    enabled: yes
  notify:
    - Update APT cache

- name: Add DBeaver APT repository
  ansible.builtin.deb822_repository:
    name: dbeaver
    types: [deb]
    uris: https://dbeaver.io/debs/dbeaver-ce
    signed_by: https://dbeaver.io/debs/dbeaver.gpg.key
    suites: [/]
    state: present
    enabled: yes
  notify:
    - Update APT cache

- name: Add NordVPN APT repository
  ansible.builtin.deb822_repository:
    name: nordvpn
    types: [deb]
    uris: https://repo.nordvpn.com/deb/nordvpn/debian
    signed_by: https://repo.nordvpn.com//gpg/nordvpn_public.asc
    suites: [stable]
    components: [main]
    state: present
    enabled: yes
  notify:
    - Update APT cache

- name: Add NodeSource APT repository
  ansible.builtin.deb822_repository:
    name: nodesource
    types: [deb]
    uris: https://deb.nodesource.com/node_20.x
    signed_by: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
    architectures: amd64
    suites: [nodistro]
    components: [main]
    state: present
    enabled: yes
  notify:
    - Update APT cache

- name: Add HashiCorp APT repository
  ansible.builtin.deb822_repository:
    name: hashicorp
    types: [deb]
    uris: https://apt.releases.hashicorp.com
    signed_by: https://apt.releases.hashicorp.com/gpg
    architectures: amd64
    suites: ["{{ ubuntu_codename | lower }}"]
    components: [main]
    state: present
    enabled: yes
  notify:
    - Update APT cache

- meta: flush_handlers