---
- name: Create terraform.d directory
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/.terraform.d"
    state: directory
    mode: '0700'

- name: Create plugin cache directory
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/.terraform.d/plugin-cache"
    state: directory
    mode: '0700'

- name: Set opentofu plugin cache directory
  ansible.builtin.lineinfile:
    path: "{{ ansible_facts['env']['HOME'] }}/.bashrc"
    line: 'export TF_PLUGIN_CACHE_DIR="$HOME/.terraform.d/plugin-cache"'
    state: present