---
- name: Install packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - cifs-utils
    - curl
    - xserver-xorg-input-synaptics
    - xz-utils
    - gnupg
    - software-properties-common
    - ffmpeg
    - git
    - jq

- name: Install apt applications
  ansible.builtin.apt:
    name: "{{ item }}"  
    state: present
  with_items:
    - brave-origin
    - kate
    - code # Visual Studio Code
    - vlc
    - qdirstat
    - flameshot
    - kopia-ui
    - sourcegit

- name: Install flatpak applications
  community.general.flatpak:
    name: "{{ item }}"
    state: present
  with_items:
    - com.github.tchx84.Flatseal
    - io.dbeaver.DBeaverCommunity