---
- name: Add Brave Origin APT repository
  ansible.builtin.deb822_repository:
    name: brave-browser
    types: [deb]
    uris: https://brave-browser-apt-release.s3.brave.com
    signed_by: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    suites: [stable]
    components: [main]
    state: present
    enabled: yes
  notify:
    - Update APT cache

- name: Add VS Code APT repository
  ansible.builtin.deb822_repository:
    name: vscode
    types: [deb]
    uris: https://packages.microsoft.com/repos/code
    signed_by: https://packages.microsoft.com/keys/microsoft.asc
    architectures: amd64
    suites: [stable]
    components: [main]
    state: present
    enabled: yes
  notify:
    - Update APT cache

- name: Add Kopia APT repository
  ansible.builtin.deb822_repository:
    name: kopia
    types: [deb]
    uris: http://packages.kopia.io/apt/
    signed_by: https://kopia.io/signing-key
    suites: [stable]
    components: [main]
    state: present
    enabled: yes
  notify:
    - Update APT cache

- name: Add SourceGit APT repository
  ansible.builtin.deb822_repository:
    name: sourcegit
    types: [deb]
    uris: https://codeberg.org/api/packages/yataro/debian
    signed_by: https://codeberg.org/api/packages/yataro/debian/repository.key
    architectures: amd64
    suites: [generic]
    components: [main]
    state: present
    enabled: yes
  notify:
    - Update APT cache  

- meta: flush_handlers