---
- name: Provision linux server
  hosts: localhost
  become: yes
  roles:
    - ../roles/software
    - ../roles/configurations

- name: Provision user configurations
  hosts: localhost
  roles:
    - ../roles/configurations_user