---
- name: Install docker engine
  ansible.builtin.dnf:
    name: "{{ item }}"  
    state: present
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_facts['user_id'] }}"
    groups: docker
    append: true

- name: Enable and start Docker
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started