---
- name: Uninstall default packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: absent
    autoremove: true
  become: yes
  loop:
    - "@libreoffice"
    - libreoffice*

- name: Enable RPM Fusion
  ansible.builtin.dnf:
    name:
      - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_facts['distribution_major_version'] }}.noarch.rpm"
      - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_facts['distribution_major_version'] }}.noarch.rpm"
    disable_gpg_check: false
    state: present
  become: yes
  tags:
    - packages
    - apps

- name: Add RPM repositories
  ansible.builtin.include_tasks: 
    file: repositories.yml
    apply:
      become: yes
      tags:
        - packages
        - apps
  tags:
    - packages
    - apps

- name: Install Packages
  ansible.builtin.include_tasks: 
    file: packages.yml
    apply:
      become: yes
      tags:
        - packages
        - apps
  tags:
    - packages
    - apps

- name: Install Docker
  ansible.builtin.include_tasks: 
    file: docker.yml
    apply:
      become: yes
      tags:
        - docker
  tags:
    - docker

- name: Install Mise
  ansible.builtin.include_tasks: 
    file: mise.yml
    apply:
      tags:
        - mise
        - tools
  tags:
    - mise
    - tools