---
- name: Create mise config path
  ansible.builtin.file: 
    path: ~/.config/mise
    state: directory
  become: no

- name: Write global mise config file
  ansible.builtin.copy:
    src: mise.global.toml
    dest: ~/.config/mise/config.toml
    mode: '0644'
  become: no

- name: Add mise activation to .bashrc
  ansible.builtin.lineinfile:
    path: "~/.bashrc"
    line: 'eval "$(mise activate bash)"'
    create: true
    mode: '0644'
  become: no