---
- name: Install common packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - ca-certificates
    - cifs-utils
    - curl
    - git
    - xz
    - gnupg2

- name: Install rpm fusion packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    allowerasing: yes
    state: present
  loop:
    - ffmpeg

- name: Install applications and tools
  ansible.builtin.dnf:
    name: "{{ item }}"  
    state: present
  loop:
    - brave-origin
    - code # VS Code
    - vlc
    - qdirstat
    - kate
    - sourcegit
    - jq
    - flameshot

- name: Install flatpak applications
  community.general.flatpak:
    name: "{{ item }}"
    state: present
  loop:
    # - com.github.tchx84.Flatseal
    - com.spotify.Client
    - io.dbeaver.DBeaverCommunity
    - com.usebruno.Bruno
    # - com.borgbase.Vorta