---
- name: Create mise config path
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/.config/mise"
    state: directory

- name: Write global mise config file
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../../../common/files/mise.global.toml"
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/mise/config.toml"
    mode: '0644'

- name: Add mise activation to .bashrc
  ansible.builtin.lineinfile:
    path: "{{ ansible_facts['env']['HOME'] }}/.bashrc"
    line: 'eval "$(mise activate bash)"'
    state: present